### ISSUE TITLE
Is this package/project still active ?

### ISSUE THREAD

**Issue by vojtechmares** [shoptet/spayd-php#1]
Hello, 

I am writting in order to find out if it would be helpful to send a PR updating this library to latest PHP features such as strict types, typehints etc. 

Is it interesting to you @Shoptet or this is dead ?

**Comment by jaroslavtyc** [comment]
Well, its really long time:D From the original team remains only @lebeda 
Also the shoptet/spayd-php library is not even listed in packagist.org (composer) so... maybe is the right time to fork it, tune it up and publish it under your name as a composer package.-)
If you get stuck with that, I can help.

**Comment by vojtechmares** [comment]
@jaroslavtyc I know it is a really loooong time, that is the reason why I am asking. 

I know that @sunfoxcz has a fork available on Packagist, but I want to update it to PHP 7.3, types, add phpstan and other fancy stuff :D

Ok, I will do it in some time then :)

**Comment by jaroslavtyc** [comment]
@vojtamares Try https://github.com/rectorphp/rector by @rectorphp, it can do a **lot** of that automatically (currently from PHP 5.3 up to 7.4)
